/**
 * Generates docs/tools.md and docs/coverage.md from the tool registry and the OpenAPI
 * snapshot, so documentation never drifts from the code.
 *
 *   npm run docs:generate
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { EXCLUDED_OPERATIONS } from '../src/tools/coverage.js';
import { ALL_TOOLS } from '../src/tools/index.js';
import { annotationsFor } from '../src/tools/registry.js';
import { DEFAULT_TOOLSETS, TOOLSETS } from '../src/tools/toolsets.js';

const root = (path: string) => fileURLToPath(new URL(`../${path}`, import.meta.url));

const HEADER = '<!-- GENERATED by scripts/gen-docs.ts — do not edit by hand. -->\n\n';
const ACCESS_LABEL = {
  read: 'read-only',
  write: 'write (`safe` mode)',
  destructive: 'destructive (`full` mode)',
} as const;

type JsonSchema = {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
};

function typeLabel(schema: JsonSchema): string {
  if (schema.enum) return schema.enum.map((v) => `\`${String(v)}\``).join(' \\| ');
  if (schema.anyOf) return schema.anyOf.map(typeLabel).join(' \\| ');
  if (schema.type === 'array') return `${schema.items ? typeLabel(schema.items) : 'any'}[]`;
  return Array.isArray(schema.type) ? schema.type.join(' \\| ') : (schema.type ?? 'any');
}

const escapeCell = (text: string) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function toolsMarkdown(): string {
  const lines = [
    '# Tools',
    '',
    'Tools are grouped into toolsets. Enable them with `INTERVALS_ICU_TOOLSETS` ' +
      `(default: ${DEFAULT_TOOLSETS.map((t) => `\`${t}\``).join(', ')}). Write tools also ` +
      'depend on `INTERVALS_ICU_WRITE_MODE`.',
    '',
  ];
  for (const toolset of TOOLSETS) {
    const tools = ALL_TOOLS.filter((t) => t.toolset === toolset);
    if (tools.length === 0) continue;
    const suffix = DEFAULT_TOOLSETS.includes(toolset) ? '' : ' (opt-in)';
    lines.push(`## \`${toolset}\`${suffix}`, '');
    for (const tool of tools) {
      const schema = z.toJSONSchema(tool.input, {
        io: 'input',
        unrepresentable: 'any',
      }) as JsonSchema;
      const hints = annotationsFor(tool);
      lines.push(
        `### \`${tool.name}\``,
        '',
        `**${tool.title}** · ${ACCESS_LABEL[tool.access as keyof typeof ACCESS_LABEL]}` +
          (hints.idempotentHint && tool.access !== 'read' ? ' · idempotent' : ''),
        '',
        tool.description,
        '',
      );
      const properties = Object.entries(schema.properties ?? {});
      if (properties.length > 0) {
        lines.push('| Parameter | Type | Required | Description |', '|---|---|---|---|');
        for (const [name, prop] of properties) {
          const required = schema.required?.includes(name) ? 'yes' : '';
          lines.push(
            `| \`${name}\` | ${typeLabel(prop)} | ${required} | ${escapeCell(prop.description ?? '')} |`,
          );
        }
        lines.push('');
      }
      lines.push(`API: ${tool.operations.map((op: string) => `\`${op}\``).join(', ')}`, '');
    }
  }
  return HEADER + lines.join('\n');
}

type Spec = {
  paths: Record<
    string,
    Record<string, { operationId?: string; tags?: string[]; summary?: string }>
  >;
};

async function coverageMarkdown(): Promise<string> {
  const spec: Spec = JSON.parse(await readFile(root('openapi/intervals-icu.openapi.json'), 'utf8'));
  const coveredBy = new Map<string, string[]>();
  for (const tool of ALL_TOOLS) {
    for (const op of tool.operations as string[]) {
      coveredBy.set(op, [...(coveredBy.get(op) ?? []), tool.name]);
    }
  }

  const byTag = new Map<string, Array<{ id: string; method: string; path: string }>>();
  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(item)) {
      if (!op.operationId) continue;
      const tag = op.tags?.[0] ?? 'Other';
      byTag.set(tag, [...(byTag.get(tag) ?? []), { id: op.operationId, method, path }]);
    }
  }

  const all = [...byTag.values()].flat();
  const covered = all.filter((o) => coveredBy.has(o.id)).length;
  const excluded = all.filter((o) => !coveredBy.has(o.id) && o.id in EXCLUDED_OPERATIONS).length;
  const planned = all.length - covered - excluded;

  const lines = [
    '# API coverage',
    '',
    `Intervals.icu API operations (from the OpenAPI snapshot) and the tools that cover them.`,
    '',
    '| Status | Operations |',
    '|---|---|',
    `| ✅ Covered | ${covered} |`,
    `| ⛔ Excluded on purpose | ${excluded} |`,
    `| ⏳ Planned | ${planned} |`,
    `| **Total** | **${all.length}** |`,
    '',
  ];
  for (const [tag, ops] of [...byTag.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`## ${tag}`, '', '| Operation | Endpoint | Status |', '|---|---|---|');
    for (const op of ops.sort((a, b) => a.id.localeCompare(b.id))) {
      const tools = coveredBy.get(op.id);
      const reason = EXCLUDED_OPERATIONS[op.id as keyof typeof EXCLUDED_OPERATIONS];
      const status = tools
        ? `✅ ${tools.map((t) => `\`${t}\``).join(', ')}`
        : reason
          ? `⛔ ${reason}`
          : '⏳ planned';
      lines.push(`| \`${op.id}\` | \`${op.method.toUpperCase()} ${op.path}\` | ${status} |`);
    }
    lines.push('');
  }
  return HEADER + lines.join('\n');
}

await writeFile(root('docs/tools.md'), toolsMarkdown());
await writeFile(root('docs/coverage.md'), await coverageMarkdown());
console.error('Generated docs/tools.md and docs/coverage.md');
